spring:
  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
      first-name: Admin

server:
  port: 8082